### ISSUE TITLE
Generate build files failed

### ISSUE THREAD

**Issue by mldb** [react-native-skia/react-native-skia#23]
Hi
after run this command
` gn gen --args='mac_deployment_target="10.15.5" mac_min_system_version="10.11.0" is_debug=false' out/Release`
i get this:
`ERROR at //rns_shell/rns_shell.gni:29:6: Undefined identifier`

**Comment by pprabhu-ng** [comment]
@mldb  rns_shell which was added recently, replaces the previous sk_app usage. This error is from rns_shell which currently supports linux platforms. It does not have support for macOS builds and hence this error.
This information update in the readme is missed. 

FYI : rns_shell was integrated at commit #d609f0e. Builds previous to this commit would work for both linux and macOS.

**Comment by Kudo** [comment]
macos is broken in the meantime. to speed up development react-native-skia, we are now focusing linux first. i will try to find some available time to add macos support back.

**Comment by munezbn** [comment]
@mldb If you still want to try the initial version on macos then you can try our downstream with [tag v0.1](https://github.com/nagra-opentv/react-native-skia/tree/v0.1.0)

**Comment by mldb** [comment]
@Kudo @munezbn thanks 🙏
