### ISSUE TITLE
Blankpage when canvas used iniside flatlist

### ISSUE THREAD

**Issue by Sreelakshmi192** [react-native-skia/react-native-skia#44]
Below given is my code and i am always getting blankpage if i put canvas inside flatlist ..Did i do any mistake..?

![Screenshot_1648096172](https://user-images.githubusercontent.com/102274513/159842503-3c52d5c6-74a3-4c48-87d4-30fa803094b9.png)

import React, { useState } from "react";
import { FlatList, SafeAreaView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Canvas, Image, useImage } from "@shopify/react-native-skia";

const App = () => {
  const [selectedId, setSelectedId] = useState(null);
  const image = useImage(require("../../assets/images/png/krish.jpeg"));

  const renderItem = () => {
    return (
          <Canvas style={{ flex: 1 }}>
     {image && (
        <Image
          image={image}
          fit="contain"
          x={0}
          y={0}
          width={256}
          height={256}
        />
      )}
    </Canvas>
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <FlatList
        data={[1,2]}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        extraData={selectedId}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0,
  },
  item: {
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 32,
  },
});

export default App;

**Comment by Kudo** [comment]
hi there! sorry to confuse but you should probably open the issue at https://github.com/Shopify/react-native-skia
